// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	release_raspi_com "github.com/andrew-bodine/raspi/release/pkg/protobufs"
	"github.com/andrew-bodine/raspi/release/pkg/proxy"
)

type FakeReleaseLister struct {
	Stub        func(*proxy.ReleaseListOptions) []release_raspi_com.Release
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 *proxy.ReleaseListOptions
	}
	returns struct {
		result1 []release_raspi_com.Release
	}
	returnsOnCall map[int]struct {
		result1 []release_raspi_com.Release
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReleaseLister) Spy(arg1 *proxy.ReleaseListOptions) []release_raspi_com.Release {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 *proxy.ReleaseListOptions
	}{arg1})
	fake.recordInvocation("ReleaseLister", []interface{}{arg1})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *FakeReleaseLister) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeReleaseLister) Calls(stub func(*proxy.ReleaseListOptions) []release_raspi_com.Release) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeReleaseLister) ArgsForCall(i int) *proxy.ReleaseListOptions {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *FakeReleaseLister) Returns(result1 []release_raspi_com.Release) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 []release_raspi_com.Release
	}{result1}
}

func (fake *FakeReleaseLister) ReturnsOnCall(i int, result1 []release_raspi_com.Release) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 []release_raspi_com.Release
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 []release_raspi_com.Release
	}{result1}
}

func (fake *FakeReleaseLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReleaseLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ proxy.ReleaseLister = new(FakeReleaseLister).Spy
