// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/andrew-bodine/monitor/pkg/monitors"
)

type FakeMonitorBuilder struct {
	Stub        func(interface{}) (monitors.Monitor, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 interface{}
	}
	returns struct {
		result1 monitors.Monitor
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 monitors.Monitor
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMonitorBuilder) Spy(arg1 interface{}) (monitors.Monitor, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("MonitorBuilder", []interface{}{arg1})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *FakeMonitorBuilder) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeMonitorBuilder) Calls(stub func(interface{}) (monitors.Monitor, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeMonitorBuilder) ArgsForCall(i int) interface{} {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *FakeMonitorBuilder) Returns(result1 monitors.Monitor, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeMonitorBuilder) ReturnsOnCall(i int, result1 monitors.Monitor, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 monitors.Monitor
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeMonitorBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMonitorBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ monitors.MonitorBuilder = new(FakeMonitorBuilder).Spy
