// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	temperature_monitor "github.com/andrew-bodine/raspi/monitor/pkg/temperature-monitor"
)

type FakeDHT11Sensor struct {
	ReadStub        func() *temperature_monitor.DHT11Result
	readMutex       sync.RWMutex
	readArgsForCall []struct {
	}
	readReturns struct {
		result1 *temperature_monitor.DHT11Result
	}
	readReturnsOnCall map[int]struct {
		result1 *temperature_monitor.DHT11Result
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDHT11Sensor) Read() *temperature_monitor.DHT11Result {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
	}{})
	stub := fake.ReadStub
	fakeReturns := fake.readReturns
	fake.recordInvocation("Read", []interface{}{})
	fake.readMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDHT11Sensor) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeDHT11Sensor) ReadCalls(stub func() *temperature_monitor.DHT11Result) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *FakeDHT11Sensor) ReadReturns(result1 *temperature_monitor.DHT11Result) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 *temperature_monitor.DHT11Result
	}{result1}
}

func (fake *FakeDHT11Sensor) ReadReturnsOnCall(i int, result1 *temperature_monitor.DHT11Result) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 *temperature_monitor.DHT11Result
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 *temperature_monitor.DHT11Result
	}{result1}
}

func (fake *FakeDHT11Sensor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDHT11Sensor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ temperature_monitor.DHT11Sensor = new(FakeDHT11Sensor)
