// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/andrew-bodine/raspi/monitor/pkg/monitors"
	"github.com/andrew-bodine/raspi/monitor/pkg/registry"
)

type FakeRegistry struct {
	GetRegisteredMonitorStub        func() (monitors.Monitor, error)
	getRegisteredMonitorMutex       sync.RWMutex
	getRegisteredMonitorArgsForCall []struct {
	}
	getRegisteredMonitorReturns struct {
		result1 monitors.Monitor
		result2 error
	}
	getRegisteredMonitorReturnsOnCall map[int]struct {
		result1 monitors.Monitor
		result2 error
	}
	GetRegisteredMonitorsStub        func() ([]monitors.Monitor, error)
	getRegisteredMonitorsMutex       sync.RWMutex
	getRegisteredMonitorsArgsForCall []struct {
	}
	getRegisteredMonitorsReturns struct {
		result1 []monitors.Monitor
		result2 error
	}
	getRegisteredMonitorsReturnsOnCall map[int]struct {
		result1 []monitors.Monitor
		result2 error
	}
	RegisterMonitorStub        func(string, monitors.Monitor) error
	registerMonitorMutex       sync.RWMutex
	registerMonitorArgsForCall []struct {
		arg1 string
		arg2 monitors.Monitor
	}
	registerMonitorReturns struct {
		result1 error
	}
	registerMonitorReturnsOnCall map[int]struct {
		result1 error
	}
	UnregisterMonitorStub        func(string) error
	unregisterMonitorMutex       sync.RWMutex
	unregisterMonitorArgsForCall []struct {
		arg1 string
	}
	unregisterMonitorReturns struct {
		result1 error
	}
	unregisterMonitorReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRegistry) GetRegisteredMonitor() (monitors.Monitor, error) {
	fake.getRegisteredMonitorMutex.Lock()
	ret, specificReturn := fake.getRegisteredMonitorReturnsOnCall[len(fake.getRegisteredMonitorArgsForCall)]
	fake.getRegisteredMonitorArgsForCall = append(fake.getRegisteredMonitorArgsForCall, struct {
	}{})
	stub := fake.GetRegisteredMonitorStub
	fakeReturns := fake.getRegisteredMonitorReturns
	fake.recordInvocation("GetRegisteredMonitor", []interface{}{})
	fake.getRegisteredMonitorMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRegistry) GetRegisteredMonitorCallCount() int {
	fake.getRegisteredMonitorMutex.RLock()
	defer fake.getRegisteredMonitorMutex.RUnlock()
	return len(fake.getRegisteredMonitorArgsForCall)
}

func (fake *FakeRegistry) GetRegisteredMonitorCalls(stub func() (monitors.Monitor, error)) {
	fake.getRegisteredMonitorMutex.Lock()
	defer fake.getRegisteredMonitorMutex.Unlock()
	fake.GetRegisteredMonitorStub = stub
}

func (fake *FakeRegistry) GetRegisteredMonitorReturns(result1 monitors.Monitor, result2 error) {
	fake.getRegisteredMonitorMutex.Lock()
	defer fake.getRegisteredMonitorMutex.Unlock()
	fake.GetRegisteredMonitorStub = nil
	fake.getRegisteredMonitorReturns = struct {
		result1 monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) GetRegisteredMonitorReturnsOnCall(i int, result1 monitors.Monitor, result2 error) {
	fake.getRegisteredMonitorMutex.Lock()
	defer fake.getRegisteredMonitorMutex.Unlock()
	fake.GetRegisteredMonitorStub = nil
	if fake.getRegisteredMonitorReturnsOnCall == nil {
		fake.getRegisteredMonitorReturnsOnCall = make(map[int]struct {
			result1 monitors.Monitor
			result2 error
		})
	}
	fake.getRegisteredMonitorReturnsOnCall[i] = struct {
		result1 monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) GetRegisteredMonitors() ([]monitors.Monitor, error) {
	fake.getRegisteredMonitorsMutex.Lock()
	ret, specificReturn := fake.getRegisteredMonitorsReturnsOnCall[len(fake.getRegisteredMonitorsArgsForCall)]
	fake.getRegisteredMonitorsArgsForCall = append(fake.getRegisteredMonitorsArgsForCall, struct {
	}{})
	stub := fake.GetRegisteredMonitorsStub
	fakeReturns := fake.getRegisteredMonitorsReturns
	fake.recordInvocation("GetRegisteredMonitors", []interface{}{})
	fake.getRegisteredMonitorsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRegistry) GetRegisteredMonitorsCallCount() int {
	fake.getRegisteredMonitorsMutex.RLock()
	defer fake.getRegisteredMonitorsMutex.RUnlock()
	return len(fake.getRegisteredMonitorsArgsForCall)
}

func (fake *FakeRegistry) GetRegisteredMonitorsCalls(stub func() ([]monitors.Monitor, error)) {
	fake.getRegisteredMonitorsMutex.Lock()
	defer fake.getRegisteredMonitorsMutex.Unlock()
	fake.GetRegisteredMonitorsStub = stub
}

func (fake *FakeRegistry) GetRegisteredMonitorsReturns(result1 []monitors.Monitor, result2 error) {
	fake.getRegisteredMonitorsMutex.Lock()
	defer fake.getRegisteredMonitorsMutex.Unlock()
	fake.GetRegisteredMonitorsStub = nil
	fake.getRegisteredMonitorsReturns = struct {
		result1 []monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) GetRegisteredMonitorsReturnsOnCall(i int, result1 []monitors.Monitor, result2 error) {
	fake.getRegisteredMonitorsMutex.Lock()
	defer fake.getRegisteredMonitorsMutex.Unlock()
	fake.GetRegisteredMonitorsStub = nil
	if fake.getRegisteredMonitorsReturnsOnCall == nil {
		fake.getRegisteredMonitorsReturnsOnCall = make(map[int]struct {
			result1 []monitors.Monitor
			result2 error
		})
	}
	fake.getRegisteredMonitorsReturnsOnCall[i] = struct {
		result1 []monitors.Monitor
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) RegisterMonitor(arg1 string, arg2 monitors.Monitor) error {
	fake.registerMonitorMutex.Lock()
	ret, specificReturn := fake.registerMonitorReturnsOnCall[len(fake.registerMonitorArgsForCall)]
	fake.registerMonitorArgsForCall = append(fake.registerMonitorArgsForCall, struct {
		arg1 string
		arg2 monitors.Monitor
	}{arg1, arg2})
	stub := fake.RegisterMonitorStub
	fakeReturns := fake.registerMonitorReturns
	fake.recordInvocation("RegisterMonitor", []interface{}{arg1, arg2})
	fake.registerMonitorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRegistry) RegisterMonitorCallCount() int {
	fake.registerMonitorMutex.RLock()
	defer fake.registerMonitorMutex.RUnlock()
	return len(fake.registerMonitorArgsForCall)
}

func (fake *FakeRegistry) RegisterMonitorCalls(stub func(string, monitors.Monitor) error) {
	fake.registerMonitorMutex.Lock()
	defer fake.registerMonitorMutex.Unlock()
	fake.RegisterMonitorStub = stub
}

func (fake *FakeRegistry) RegisterMonitorArgsForCall(i int) (string, monitors.Monitor) {
	fake.registerMonitorMutex.RLock()
	defer fake.registerMonitorMutex.RUnlock()
	argsForCall := fake.registerMonitorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRegistry) RegisterMonitorReturns(result1 error) {
	fake.registerMonitorMutex.Lock()
	defer fake.registerMonitorMutex.Unlock()
	fake.RegisterMonitorStub = nil
	fake.registerMonitorReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRegistry) RegisterMonitorReturnsOnCall(i int, result1 error) {
	fake.registerMonitorMutex.Lock()
	defer fake.registerMonitorMutex.Unlock()
	fake.RegisterMonitorStub = nil
	if fake.registerMonitorReturnsOnCall == nil {
		fake.registerMonitorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerMonitorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRegistry) UnregisterMonitor(arg1 string) error {
	fake.unregisterMonitorMutex.Lock()
	ret, specificReturn := fake.unregisterMonitorReturnsOnCall[len(fake.unregisterMonitorArgsForCall)]
	fake.unregisterMonitorArgsForCall = append(fake.unregisterMonitorArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.UnregisterMonitorStub
	fakeReturns := fake.unregisterMonitorReturns
	fake.recordInvocation("UnregisterMonitor", []interface{}{arg1})
	fake.unregisterMonitorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRegistry) UnregisterMonitorCallCount() int {
	fake.unregisterMonitorMutex.RLock()
	defer fake.unregisterMonitorMutex.RUnlock()
	return len(fake.unregisterMonitorArgsForCall)
}

func (fake *FakeRegistry) UnregisterMonitorCalls(stub func(string) error) {
	fake.unregisterMonitorMutex.Lock()
	defer fake.unregisterMonitorMutex.Unlock()
	fake.UnregisterMonitorStub = stub
}

func (fake *FakeRegistry) UnregisterMonitorArgsForCall(i int) string {
	fake.unregisterMonitorMutex.RLock()
	defer fake.unregisterMonitorMutex.RUnlock()
	argsForCall := fake.unregisterMonitorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRegistry) UnregisterMonitorReturns(result1 error) {
	fake.unregisterMonitorMutex.Lock()
	defer fake.unregisterMonitorMutex.Unlock()
	fake.UnregisterMonitorStub = nil
	fake.unregisterMonitorReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRegistry) UnregisterMonitorReturnsOnCall(i int, result1 error) {
	fake.unregisterMonitorMutex.Lock()
	defer fake.unregisterMonitorMutex.Unlock()
	fake.UnregisterMonitorStub = nil
	if fake.unregisterMonitorReturnsOnCall == nil {
		fake.unregisterMonitorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unregisterMonitorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getRegisteredMonitorMutex.RLock()
	defer fake.getRegisteredMonitorMutex.RUnlock()
	fake.getRegisteredMonitorsMutex.RLock()
	defer fake.getRegisteredMonitorsMutex.RUnlock()
	fake.registerMonitorMutex.RLock()
	defer fake.registerMonitorMutex.RUnlock()
	fake.unregisterMonitorMutex.RLock()
	defer fake.unregisterMonitorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ registry.Registry = new(FakeRegistry)
